rules:
  artipacked:
    ignore:
      - generate.yml:46 # generate creates an automated release and creates a PR
      - publish-gem.yml:66 # publish-gem adds and pushes a tag
  secrets-outside-env:
    config:
      allow:
        - FACTOTUM_APP_PRIVATE_KEY
